# Generated by Django 4.2.2 on 2023-06-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('date_of_service', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bill_picture', models.ImageField(upload_to='bills/')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
